name: robustpointclouds
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - cudatoolkit=11.5
  - git
  - pip
  - pytorch==1.11
  - torchvision
  - torchaudio
  - shapely
  - pip:
    - -r requirements.txt